### ISSUE TITLE
No error handling when inputting a non-number in grade score

### ISSUE THREAD

**Issue by carolinaisslaying** [jacksonrakena/gradekeeper#12]
When attempting to to input a non-number in the grade score input box, it infinitely loads out.

Screen recording of the issue:

https://github.com/user-attachments/assets/660f914d-1ccd-4225-8901-875fa0a49baa

Error shown in the browser console:

<img width="814" alt="image" src="https://github.com/user-attachments/assets/0c6ea3d0-d1d6-4f3a-a4ce-ff065a4fde12">

**Comment by carolinaisslaying** [comment]
Going off of this, providing additional functionality like being able to type in "15/20" and it converting it to a percentage automatically (75%), particularly for more complex grades, could be useful (to prevent people having to pull out a calculator or open a new website to calculate the percentage).

**Comment by jacksonrakena** [comment]
Yeah, I think it would be good for the `Editable.onSubmit` on the grade value input instances to automatically parse fractions, although the implementation will have to possibly use something like [Math.js](https://mathjs.org/docs/expressions/parsing.html), using the native JS `eval()` function is unsafe and would allow users to inject custom JavaScript (as well as just be a bit messy).

**Comment by jacksonrakena** [comment]
Implemented in https://github.com/jacksonrakena/gradekeeper/commit/1fc876a9499b28013e878cd41079fb6c5d3709b1
