### ISSUE TITLE
Year in new term preset is off for Trimester 3

### ISSUE THREAD

**Issue by carolinaisslaying** [jacksonrakena/gradekeeper#13]
When attempting to create a new term, the Trimester 3 preset shows 2023 as the date, but it selects the 2024-2025 dates instead.

<img width="602" alt="image" src="https://github.com/user-attachments/assets/a47b2a0c-bfee-42ad-8dee-4cce681872d7">

**Comment by jacksonrakena** [comment]
Fixed in [bf3c758](https://github.com/jacksonrakena/gradekeeper/commit/bf3c758fc0953567043f363f6d46703427e7569c)
